(()=>{const v={home:document.getElementById('view-home'),experience:document.getElementById('view-experience'),projects:document.getElementById('view-projects'),education:document.getElementById('view-education'),contact:document.getElementById('view-contact'),resume:document.getElementById('view-resume')};
const s={projects:[],experience:[],education:[],favorites:new Set(JSON.parse(localStorage.getItem('favorites')||'[]')),tags:new Set()};
const $=(q,r=document)=>r.querySelector(q),$$=(q,r=document)=>Array.from(r.querySelectorAll(q));
const setTheme=t=>document.documentElement.dataset.theme=t;const pref=localStorage.getItem('theme');if(pref)setTheme(pref);
document.getElementById('theme-toggle').addEventListener('click',()=>{const n=(document.documentElement.dataset.theme==='light')?'':'light';if(n)localStorage.setItem('theme',n);else localStorage.removeItem('theme');setTheme(n)});
document.getElementById('year').textContent=new Date().getFullYear();
function selectTab(id){$$('.nav-links a').forEach(a=>a.setAttribute('aria-selected',String(a.getAttribute('href')==='#'+id)));}
function route(){const h=location.hash.replace('#','')||'home';Object.values(v).forEach(x=>x.hidden=!0);(v[h]||v.home).hidden=!1;selectTab(h);v[h]?.focus?.();if(h==='projects')renderProjects();if(h==='experience')renderExperience();if(h==='education')renderEducation();if(h==='resume')renderResume();}
window.addEventListener('hashchange',route);route();
Promise.all([fetch('data/projects.json').then(r=>r.json()),fetch('data/experience.json').then(r=>r.json()),fetch('data/education.json').then(r=>r.json())]).then(([p,e,d])=>{s.projects=p;s.experience=e;s.education=d;
document.getElementById('stat-projects').textContent=p.length;document.getElementById('stat-years').textContent=e.reduce((a,x)=>a+(x.years||0),0);document.getElementById('stat-awards').textContent=d.reduce((a,x)=>a+(x.awards?.length||0),0);
p.forEach(pr=>(pr.tags||[]).forEach(t=>s.tags.add(t)));renderTagChips();route();}).catch(e=>console.warn('Data load error',e));
let g=false;window.addEventListener('keydown',e=>{if(e.key==='/'){if(location.hash==='#projects'){$('#proj-search').focus();e.preventDefault();}}else if(e.key==='?'){toggleHelp();}else if(e.key.toLowerCase()==='g'){g=true;setTimeout(()=>g=false,800);}else if(g){const m={e:'experience',p:'projects',d:'education',c:'contact',h:'home',r:'resume'};const t=m[e.key.toLowerCase()];if(t)location.hash=t;}});
function toggleHelp(){const t=document.getElementById('kbd-help');t.hidden=!t.hidden;setTimeout(()=>t.hidden=!0,3500);}
document.getElementById('exp-filter').addEventListener('change',renderExperience);
function esc(x){return String(x).replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));}
function renderExperience(){const list=document.getElementById('experience-timeline');list.innerHTML='';const f=document.getElementById('exp-filter').value;s.experience.filter(x=>f==='all'||(x.tags||[]).includes(f)).forEach(r=>{const li=document.createElement('li');li.innerHTML=`<div class="card"><div class="row" style="justify-content:space-between"><strong>${esc(r.title)}</strong><span class="badge">${esc(r.start)} – ${esc(r.end||'Present')}</span></div><div class="muted">${esc(r.company)} · ${esc(r.location)}</div><details class="accord"><summary>Highlights</summary><ul class="list">${(r.highlights||[]).map(h=>'<li>'+esc(h)+'</li>').join('')}</ul></details><div class="tags">${(r.tags||[]).map(t=>'<span class="tag">'+esc(t)+'</span>').join('')}</div></div>`;list.appendChild(li);});}
const tagWrap=document.getElementById('tag-chips');function renderTagChips(){tagWrap.innerHTML='';['All',...Array.from(s.tags).sort()].forEach(t=>{const b=document.createElement('button');b.className='chip';b.type='button';b.textContent=t;b.setAttribute('aria-pressed',t==='All'?'true':'false');b.addEventListener('click',()=>{$$('.chip',tagWrap).forEach(c=>c.setAttribute('aria-pressed','false'));b.setAttribute('aria-pressed','true');renderProjects();});tagWrap.appendChild(b);});}
document.getElementById('proj-search').addEventListener('input',renderProjects);document.getElementById('proj-sort').addEventListener('change',renderProjects);
function renderProjects(){const grid=document.getElementById('projects-grid');const q=document.getElementById('proj-search').value.toLowerCase();const active=$('.chip[aria-pressed="true"]',tagWrap)?.textContent||'All';const sort=document.getElementById('proj-sort').value;
let items=s.projects.filter(p=>(active==='All'||(p.tags||[]).includes(active))&&(!q||[p.title,p.summary,(p.tags||[]).join(' ')].join(' ').toLowerCase().includes(q)));
if(sort==='alpha')items.sort((a,b)=>a.title.localeCompare(b.title));if(sort==='recent')items.sort((a,b)=>(b.year||0)-(a.year||0));if(sort==='stars')items.sort((a,b)=>(s.favorites.has(b.id)-s.favorites.has(a.id))||b.year-a.year);
grid.innerHTML=items.map(cardHtml).join('');$$('.star',grid).forEach(btn=>btn.addEventListener('click',toggleStar));$$('.open',grid).forEach(btn=>btn.addEventListener('click',openModal));}
function cardHtml(p){const starred=s.favorites.has(p.id);const tags=(p.tags||[]).map(t=>`<span class="tag">${t}</span>`).join('');const links=[p.demo&&`<a href="${p.demo}" target="_blank" rel="noopener">Demo</a>`,p.repo&&`<a href="${p.repo}" target="_blank" rel="noopener">Code</a>`,p.caseStudy&&`<button class="open" data-id="${p.id}">Case study</button>`].filter(Boolean).join(' · ');
return `<article class="card">${p.image?`<img src="${p.image}" alt="${p.title} thumbnail" />`:''}<div class="row" style="justify-content:space-between"><h3>${p.title}</h3><button class="star" aria-label="Toggle favorite" aria-pressed="${starred}" data-id="${p.id}">★</button></div><p class="muted">${p.summary||''}</p><div class="tags">${tags}</div><p>${links}</p></article>`;}
function toggleStar(e){const id=e.currentTarget.dataset.id;if(s.favorites.has(id))s.favorites.delete(id);else s.favorites.add(id);localStorage.setItem('favorites',JSON.stringify(Array.from(s.favorites)));renderProjects();}
const modal=document.getElementById('project-modal');modal.addEventListener('click',e=>{if(e.target.hasAttribute('data-close'))modal.close();});
function openModal(e){const id=e.currentTarget.dataset.id;const p=s.projects.find(x=>String(x.id)===String(id));document.getElementById('modal-content').innerHTML=`<header class="row" style="justify-content:space-between"><h3>${p.title}</h3><button class="close" data-close>Close</button></header><p>${p.description||p.summary||''}</p>${(p.gallery||[]).map(src=>`<img src="${src}" alt="${p.title} image">`).join('')}<p>${p.repo?`<a href="${p.repo}" target="_blank" rel="noopener">Repository</a>`:''} ${p.demo?' · <a href="'+p.demo+'" target="_blank" rel="noopener">Live Demo</a>':''}</p>`;modal.showModal();}
function renderEducation(){const root=document.getElementById('education-cards');root.innerHTML=s.education.map(x=>`<article class="card"><div class="row" style="justify-content:space-between"><h3>${x.school}</h3><span class="badge">${x.start} – ${x.end||'Present'}</span></div><div class="muted">${x.degree} · ${x.location}</div><p>${x.summary||''}</p><div class="tags">${(x.highlights||[]).map(t=>'<span class="tag">'+t+'</span>').join('')}</div></article>`).join('');
document.getElementById('coursework-list').innerHTML=(s.education[0]?.coursework||[]).map(c=>'<li>'+c+'</li>').join('');}
document.getElementById('contact-form').addEventListener('submit',e=>{e.preventDefault();const d=new FormData(e.currentTarget);const body=encodeURIComponent(d.get('message'));const subj=encodeURIComponent('Portfolio Contact — '+d.get('name'));const to=document.getElementById('mailto').getAttribute('href').replace('mailto:','');location.href=`mailto:${to}?subject=${subj}&body=${body}%0A%0AFrom: ${encodeURIComponent(d.get('name'))} <${encodeURIComponent(d.get('email'))}>`;});
document.getElementById('copy-email').addEventListener('click',async()=>{const email='muhammad.u.anjum@gmail.com';await navigator.clipboard.writeText(email);const t=document.getElementById('kbd-help');t.textContent='Email copied to clipboard';t.hidden=!1;setTimeout(()=>t.hidden=!0,1500);});
function renderResume(){const el=document.getElementById('resume-target');const exp=s.experience.map(e=>`<div><strong>${e.title}</strong> — ${e.company} <span class="muted">(${e.start}–${e.end||'Present'})</span><ul>${(e.highlights||[]).map(h=>'<li>'+h+'</li>').join('')}</ul></div>`).join('');
el.innerHTML=`<h3>Experience</h3>${exp}<h3>Education</h3>${s.education.map(x=>`<div><strong>${x.school}</strong> — ${x.degree} (${x.start}–${x.end||'Present'})</div>`).join('')}<h3>Projects</h3>${s.projects.slice(0,6).map(p=>`<div><strong>${p.title}</strong>: ${p.summary||''}</div>`).join('')}`;}
})();